disabled_rules:
    - identifier_name
opt_in_rules:
    - collection_alignment

opening_brace:
    allow_multiline_func: true
switch_case_alignment:
    indented_cases: true
trailing_comma:
    mandatory_comma: true
