disabled_rules:
    - identifier_name
    - opening_brace
opt_in_rules:
    - collection_alignment

excluded:
    - .build
    - .swiftpm

large_tuple:
    warning: 3
    error: 4
switch_case_alignment:
    indented_cases: true
trailing_comma:
    mandatory_comma: true
