import AOCKit

public let aoc2021 = AdventOfCodeEvent(year: 2021, puzzles: [
    SonarSweep(),
    Dive(),
    BinaryDiagnostic(),
    GiantSquid(),
    HydrothermalVenture(),
    Lanternfish(),
    TreacheryOfWhales(),
    SevenSegmentSearch(),
    SmokeBasin(),
    SyntaxScoring(),
    DumboOctopus(),
    PassagePathing(),
    TransparentOrigami(),
    ExtendedPolymerization(),
    Chiton(),
    PacketDecoder(),
    TrickShot(),
    Snailfish(),
    BeaconScanner(),
    TrenchMap(),
    DiracDice(),
    ReactorReboot(),
    Amphipod(),
    ArithmeticLogicUnit(),
    SeaCucumber(),
])
