import AOCKit

public let aoc2020 = AdventOfCodeEvent(year: 2020, puzzles: [
    ReportRepair(),
    PasswordPhilosophy(),
    TobogganTrajectory(),
    PassportProcessing(),
    BinaryBoarding(),
    CustomCustoms(),
    HandyHaversacks(),
    HandheldHalting(),
    EncodingError(),
    AdapterArray(),
    SeatingSystem(),
    RainRisk(),
    ShuttleSearch(),
    DockingData(),
    RambunctiousRecitation(),
    TicketTranslation(),
    ConwayCubes(),
    OperationOrder(),
    MonsterMessages(),
    JurassicJigsaw(),
    AllergenAssessment(),
    CrabCombat(),
    CrabCups(),
    LobbyLayout(),
    ComboBreaker(),
])
