import AOCKit

AOC.run(puzzles: [
    .day(1, ReportRepair()),
    .day(2, PasswordPhilosophy()),
    .day(3, TobogganTrajectory()),
    .day(4, PassportProcessing()),
    .day(5, BinaryBoarding()),
    .day(6, CustomCustoms()),
    .day(7, HandyHaversacks()),
    .day(8, HandheldHalting()),
    .day(9, EncodingError()),
    .day(10, AdapterArray()),
    .day(11, SeatingSystem()),
    .day(12, RainRisk()),
    .day(13, ShuttleSearch()),
    .day(14, DockingData()),
    .day(15, RambunctiousRecitation()),
    .day(16, TicketTranslation()),
    .day(17, ConwayCubes()),
    .day(18, OperationOrder()),
    .day(19, MonsterMessages()),
    .day(20, JurassicJigsaw()),
    .day(21, AllergenAssessment()),
    .day(22, CrabCombat()),
    .day(23, CrabCups()),
    .day(24, LobbyLayout()),
], resultsPath: "Results/2020.json")
