import AOCKit

public let aoc2022 = AdventOfCodeEvent(year: 2022, puzzles: [
    CalorieCounting(),
    RockPaperScissors(),
    RucksackReorganization(),
    CampCleanup(),
    SupplyStacks(),
    TuningTrouble(),
    NoSpaceLeftOnDevice(),
    TreetopTreeHouse(),
    RopeBridge(),
    CathodeRayTube(),
    MonkeyInTheMiddle(),
    HillClimbingAlgorithm(),
    DistressSignal(),
    RegolithReservoir(),
    BeaconExclusionZone(),
    ProboscideaVolcanium(),
    PyroclasticFlow(),
    BoilingBoulders(),
    NotEnoughMinerals(),
    GrovePositioningSystem(),
    MonkeyMath(),
    MonkeyMap(),
    UnstableDiffusion(),
    BlizzardBasin(),
    FullOfHotAir(),
])
