import AOCKit

public let aoc2015 = AdventOfCodeEvent(
    year: 2015,
    puzzles: [
        NotQuiteLisp(),
        NoMath(),
        PerfectlySphericalHousesInAVacuum(),
        TheIdealStockingStuffer(),
        InternElves(),
        ProbablyAFireHazard(),
        SomeAssemblyRequired(),
        Matchsticks(),
        AllInASingleNight(),
        ElvesLookElvesSay(),
        CorporatePolicy(),
        JSAbacusFramework(),
        KnightsOfTheDinnerTable(),
        ReindeerOlympics(),
        ScienceForHungryPeople(),
        AuntSue(),
        NoSuchThingAsTooMuch(),
        LikeAGifForYourYard(),
        MedicineForRudolph(),
        InfiniteElvesAndInfiniteHouses(),
        RPGSimulator(),
        WizardSimulator(),
        OpeningTheTuringLock(),
        ItHangsInTheBalance(),
        LetItSnow(),
    ],
)
