import AOCKit

AdventOfCode(year: 2023, puzzles: [
    Trebuchet(),
    CubeConundrum(),
    GearRatios(),
    Scratchcards(),
    Seeds(),
    WaitForIt(),
    CamelCards(),
    HauntedWasteland(),
    MirageMaintenance(),
    PipeMaze(),
    CosmicExpansion(),
    HotSprings(),
    PointOfIncidence(),
    ParabolicReflectorDish(),
    LensLibrary(),
    TheFloorWillBeLava(),
    ClumsyCrucible(),
    LavaductLagoon(),
    Aplenty(),
    PulsePropagation(),
    StepCounter(),
    SandSlabs(),
]).run()
