import AOCKit

public let aoc2024 = AdventOfCodeEvent(year: 2024, puzzles: [
    HistorianHysteria(),
    RedNosedReports(),
    MullItOver(),
    CeresSearch(),
    PrintQueue(),
    GuardGallivant(),
    BridgeRepair(),
    ResonantCollinearity(),
    DiskFragmenter(),
    HoofIt(),
    PlutonianPebbles(),
    GardenGroups(),
    ClawContraption(),
    RestroomRedoubt(),
    WarehouseWoes(),
    ReindeerMaze(),
    ChronospatialComputer(),
    RamRun(),
    LinenLayout(),
    RaceCondition(),
    KeypadConundrum(),
    MonkeyMarket(),
    LanParty(),
    CrossedWires(),
    CodeChronicle(),
])
